{{- if and .Values.apiToken.value (not .Values.apiToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowsight.fullname" . }}
  labels:
    {{- include "flowsight.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.apiToken.key }}: {{ .Values.apiToken.value | b64enc | quote }}
{{- end }}
