package firewall

// Zone isolation over pf: a table per zone and block rules between them, in
// a sub-anchor of flowsight.

import (
	"fmt"
	"strings"

	"github.com/grioghar/flowsight/internal/core"
)

var _ core.Isolator = (*pfEnforcer)(nil)

func (e *pfEnforcer) RenderIsolation(spec core.IsolationSpec) string { return renderIsolation(spec) }

func renderIsolation(spec core.IsolationSpec) string {
	var b strings.Builder
	b.WriteString("# Generated by FlowSight enroll. Do not edit.\n\n")
	for _, z := range spec.Zones {
		fmt.Fprintf(&b, "table <fs_%s> persist { %s }\n", z.ID, z.Subnet)
	}
	b.WriteString("\n")
	for _, z := range spec.Zones {
		if z.Captive {
			// Captive zone: only its gateway and its DNS servers. The passes
			// come first: in pf the first matching quick rule wins, and with
			// the block first a captive client could not reach even the
			// gateway serving its captive page.
			fmt.Fprintf(&b, "pass quick from <fs_%s> to %s\n", z.ID, z.Gateway)
			for _, dns := range z.DNS {
				if dns != "" && dns != z.Gateway {
					fmt.Fprintf(&b, "pass quick proto { tcp, udp } from <fs_%s> to %s port 53\n", z.ID, dns)
				}
			}
			fmt.Fprintf(&b, "block return quick from <fs_%s> to any\n", z.ID)
			continue
		}
		for _, other := range spec.Zones {
			if other.ID == z.ID || contains(z.Reach, other.ID) {
				continue
			}
			fmt.Fprintf(&b, "block return quick from <fs_%s> to <fs_%s>\n", z.ID, other.ID)
		}
		if !z.Internet {
			fmt.Fprintf(&b, "block return quick from <fs_%s> to !<fs_%s>\n", z.ID, z.ID)
		}
	}
	return b.String()
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

// LoadIsolation checks the rules with pfctl -n and loads them into the
// sub-anchor name.
func (e *pfEnforcer) LoadIsolation(name, text string) error { return e.m.LoadAnchor(name, text) }

// ClearIsolation flushes the sub-anchor name.
func (e *pfEnforcer) ClearIsolation(name string) error { return e.m.FlushAnchor(name) }
