package firewall

import (
	"strings"
	"testing"

	"github.com/grioghar/flowsight/internal/core"
)

// The rules the enroll module's own renderer produced before it moved here,
// byte for byte, including the captive-zone fix of 0.9.8r202609262120 (the
// passes before the block). A change to these changes what every enforcing
// gateway loads.
func TestRenderIsolationGolden(t *testing.T) {
	spec := core.IsolationSpec{Zones: []core.IsolationZone{
		{ID: "trusted", Subnet: "10.99.10.0/24", Gateway: "10.99.10.1", Internet: true, Reach: []string{"iot"}},
		{ID: "iot", Subnet: "10.99.20.0/24", Gateway: "10.99.20.1", Internet: true},
		{ID: "cams", Subnet: "10.99.30.0/24", Gateway: "10.99.30.1", Internet: false},
		{ID: "guest", Subnet: "10.99.40.0/24", Gateway: "10.99.40.1", Captive: true, DNS: []string{"10.99.40.1", "1.1.1.1"}},
	}}
	want := `# Generated by FlowSight enroll. Do not edit.

table <fs_trusted> persist { 10.99.10.0/24 }
table <fs_iot> persist { 10.99.20.0/24 }
table <fs_cams> persist { 10.99.30.0/24 }
table <fs_guest> persist { 10.99.40.0/24 }

block return quick from <fs_trusted> to <fs_cams>
block return quick from <fs_trusted> to <fs_guest>
block return quick from <fs_iot> to <fs_trusted>
block return quick from <fs_iot> to <fs_cams>
block return quick from <fs_iot> to <fs_guest>
block return quick from <fs_cams> to <fs_trusted>
block return quick from <fs_cams> to <fs_iot>
block return quick from <fs_cams> to <fs_guest>
block return quick from <fs_cams> to !<fs_cams>
pass quick from <fs_guest> to 10.99.40.1
pass quick proto { tcp, udp } from <fs_guest> to 1.1.1.1 port 53
block return quick from <fs_guest> to any
`
	if got := renderIsolation(spec); got != want {
		t.Errorf("isolation rules changed:\n got: %q\nwant: %q", got, want)
	}
}

// In pf the first matching quick rule wins. A captive zone's block used to
// come before its pass to the gateway, so a captive client could reach
// nothing at all, not even the gateway serving its captive page.
func TestCaptiveZonePassesBeforeItBlocks(t *testing.T) {
	text := renderIsolation(core.IsolationSpec{Zones: []core.IsolationZone{
		{ID: "guest", Subnet: "10.99.40.0/24", Gateway: "10.99.40.1", Captive: true, DNS: []string{"10.99.40.1", "1.1.1.1"}},
	}})
	block := strings.Index(text, "block return quick from <fs_guest> to any")
	gw := strings.Index(text, "pass quick from <fs_guest> to 10.99.40.1\n")
	dns := strings.Index(text, "pass quick proto { tcp, udp } from <fs_guest> to 1.1.1.1 port 53")
	if block < 0 || gw < 0 || dns < 0 || gw > block || dns > block {
		t.Fatalf("passes must come before the block:\n%s", text)
	}
	if strings.Count(text, "to 10.99.40.1") != 1 {
		t.Fatalf("a DNS server that is the gateway needs no rule of its own:\n%s", text)
	}
}
