package firewall

import (
	"testing"

	"github.com/grioghar/flowsight/internal/core"
)

// webSpec builds the spec the web module asks for, for the golden cases.
func webSpec(ifaces, nets, excl []string, v6 string) core.RedirectSpec {
	spec := core.RedirectSpec{Interfaces: ifaces, Excluded: excl}
	if len(nets) == 0 {
		return spec
	}
	spec.Rules = []core.RedirectRule{
		{Family: "inet", Sources: nets, Port: 80, To: core.Endpoint{Addr: "127.0.0.1", Port: 3128}},
		{Family: "inet", Sources: nets, Port: 443, To: core.Endpoint{Addr: "127.0.0.1", Port: 3129}},
	}
	if v6 != "" {
		spec.Rules = append(spec.Rules,
			core.RedirectRule{Family: "inet6", Port: 80, To: core.Endpoint{Addr: v6, Port: 3128}},
			core.RedirectRule{Family: "inet6", Port: 443, To: core.Endpoint{Addr: v6, Port: 3129}})
	}
	return spec
}

// The rules the web module's own renderer produced before it moved here,
// byte for byte. A change to these is a change to what is loaded into pf on
// every gateway.
func TestRenderRedirectsGolden(t *testing.T) {
	cases := []struct {
		name string
		spec core.RedirectSpec
		want string
	}{
		{"nothing to intercept", webSpec(nil, nil, []string{"192.168.1.50"}, "fd00::1"),
			"# Generated by flowsight web module: transparent interception.\n"},
		{"one network, any interface", webSpec(nil, []string{"192.168.1.0/24"}, nil, ""),
			`# Generated by flowsight web module: transparent interception.
rdr inet proto tcp from { 192.168.1.0/24 } to ! <flowsight_local> port 80 -> 127.0.0.1 port 3128
rdr inet proto tcp from { 192.168.1.0/24 } to ! <flowsight_local> port 443 -> 127.0.0.1 port 3129
`},
		{"two interfaces, exclusions, IPv6", webSpec([]string{"vtnet0", "igb1"}, []string{"192.168.1.0/24", "10.99.0.0/16"}, []string{"192.168.1.50", "fd00::5"}, "fd00::1"),
			`# Generated by flowsight web module: transparent interception.
table <fs_web_excluded> persist { 192.168.1.50, fd00::5 }
no rdr on vtnet0 inet proto tcp from <fs_web_excluded> to any port { 80, 443 }
no rdr on vtnet0 inet6 proto tcp from <fs_web_excluded> to any port { 80, 443 }
rdr on vtnet0 inet proto tcp from { 192.168.1.0/24, 10.99.0.0/16 } to ! <flowsight_local> port 80 -> 127.0.0.1 port 3128
rdr on vtnet0 inet proto tcp from { 192.168.1.0/24, 10.99.0.0/16 } to ! <flowsight_local> port 443 -> 127.0.0.1 port 3129
rdr on vtnet0 inet6 proto tcp from <flowsight_local> to ! <flowsight_local> port 80 -> fd00::1 port 3128
rdr on vtnet0 inet6 proto tcp from <flowsight_local> to ! <flowsight_local> port 443 -> fd00::1 port 3129
no rdr on igb1 inet proto tcp from <fs_web_excluded> to any port { 80, 443 }
no rdr on igb1 inet6 proto tcp from <fs_web_excluded> to any port { 80, 443 }
rdr on igb1 inet proto tcp from { 192.168.1.0/24, 10.99.0.0/16 } to ! <flowsight_local> port 80 -> 127.0.0.1 port 3128
rdr on igb1 inet proto tcp from { 192.168.1.0/24, 10.99.0.0/16 } to ! <flowsight_local> port 443 -> 127.0.0.1 port 3129
rdr on igb1 inet6 proto tcp from <flowsight_local> to ! <flowsight_local> port 80 -> fd00::1 port 3128
rdr on igb1 inet6 proto tcp from <flowsight_local> to ! <flowsight_local> port 443 -> fd00::1 port 3129
`},
		{"one interface, IPv6", webSpec([]string{"vtnet0"}, []string{"192.168.1.0/24"}, nil, "fd00::1"),
			`# Generated by flowsight web module: transparent interception.
rdr on vtnet0 inet proto tcp from { 192.168.1.0/24 } to ! <flowsight_local> port 80 -> 127.0.0.1 port 3128
rdr on vtnet0 inet proto tcp from { 192.168.1.0/24 } to ! <flowsight_local> port 443 -> 127.0.0.1 port 3129
rdr on vtnet0 inet6 proto tcp from <flowsight_local> to ! <flowsight_local> port 80 -> fd00::1 port 3128
rdr on vtnet0 inet6 proto tcp from <flowsight_local> to ! <flowsight_local> port 443 -> fd00::1 port 3129
`},
	}
	for _, c := range cases {
		if got := renderRedirects(c.spec, "flowsight_local"); got != c.want {
			t.Errorf("%s:\n got: %q\nwant: %q", c.name, got, c.want)
		}
	}
}
