package firewall

// Interception over pf: a core.RedirectSpec becomes rdr rules in a
// sub-anchor of flowsight, loaded with pfctl and flushed to withdraw it.

import (
	"fmt"
	"strings"

	"github.com/grioghar/flowsight/internal/core"
)

var _ core.Redirector = (*pfEnforcer)(nil)

// RenderRedirects writes the rules for a redirect sub-anchor. Sources
// default to the local-networks table, and destinations in it are never
// redirected. pf has no "from A and not B" in one rule, so exclusions come
// first as "no rdr", in both families: a device excluded by its IPv4 address
// is the same device when it speaks IPv6, and exempting only half of it is
// how a television ends up intercepted on one protocol and not the other.
func (e *pfEnforcer) RenderRedirects(spec core.RedirectSpec) string {
	return renderRedirects(spec, e.m.LocalTable())
}

func renderRedirects(spec core.RedirectSpec, localTable string) string {
	var b strings.Builder
	b.WriteString("# Generated by flowsight web module: transparent interception.\n")
	if len(spec.Rules) == 0 {
		return b.String()
	}
	ifaces := spec.Interfaces
	if len(ifaces) == 0 {
		ifaces = []string{""} // any interface
	}
	if len(spec.Excluded) > 0 {
		fmt.Fprintf(&b, "table <fs_web_excluded> persist { %s }\n", strings.Join(spec.Excluded, ", "))
	}
	var ports []string
	seen := map[int]bool{}
	for _, r := range spec.Rules {
		if !seen[r.Port] {
			seen[r.Port] = true
			ports = append(ports, fmt.Sprint(r.Port))
		}
	}
	for _, ifc := range ifaces {
		on := ""
		if ifc != "" {
			on = "on " + ifc + " "
		}
		if len(spec.Excluded) > 0 {
			for _, fam := range []string{"inet", "inet6"} {
				fmt.Fprintf(&b, "no rdr %s%s proto tcp from <fs_web_excluded> to any port { %s }\n", on, fam, strings.Join(ports, ", "))
			}
		}
		for _, r := range spec.Rules {
			src := "<" + localTable + ">"
			if len(r.Sources) > 0 {
				src = "{ " + strings.Join(r.Sources, ", ") + " }"
			}
			fmt.Fprintf(&b, "rdr %s%s proto tcp from %s to ! <%s> port %d -> %s port %d\n",
				on, r.Family, src, localTable, r.Port, r.To.Addr, r.To.Port)
		}
	}
	return b.String()
}

// LoadRedirects checks the rules with pfctl -n and loads them into the
// sub-anchor name.
func (e *pfEnforcer) LoadRedirects(name, text string) error { return e.m.LoadAnchor(name, text) }

// Arrivals is empty: pf's rdr delivers to the rule's own address.
func (e *pfEnforcer) Arrivals(spec core.RedirectSpec) []string { return nil }

// ClearRedirects flushes the sub-anchor name.
func (e *pfEnforcer) ClearRedirects(name string) error { return e.m.FlushAnchor(name) }
