package firewall

// Turning the plan into pf rules.
//
// Two things about pf decide the shape of this file.
//
// Everything is matched on the LAN interface, not the WAN. On the way out
// through the WAN the source address has already been translated, so a rule
// naming a device on this network cannot match it there. On the LAN side both
// ends are still themselves.
//
// And a queue is assigned once, when the state is created, for both
// directions of that state. Writing one rule for "in" and another for "out"
// looks right and does not work: the reply travels back through the state the
// first rule made and never reaches the second. The two-argument form exists
// for exactly this, so each rule matches the direction that opens the
// connection and names both queues at once:
//
//	match in on <lan> ... dnqueue(<upload>, <download>)
//
// Measured on a test gateway with the wrong shape: the inbound rule saw 4197
// packets and the outbound rule 49, and nothing was shaped.
//
// The rules are "match" rather than "pass", which in pf applies the queue and
// carries on rather than deciding the packet's fate. Shaping should never be
// able to let something through that policy would have blocked.

import (
	"fmt"
	"strings"

	"github.com/grioghar/flowsight/internal/core"
)

// shapeTable is a pf table per rule, named from its position so that two
// rules matching similar things never collide.
func shapeTable(i int) string { return fmt.Sprintf("qos_r%d", i) }

// shapeCeilings gives each rule with a ceiling a pipe of its own per
// direction, numbered in rule order; the map is by rule key.
func shapeCeilings(p core.ShapePlan) ([]ceiling, map[string]ceiling) {
	var list []ceiling
	byKey := map[string]ceiling{}
	n := 0
	for _, r := range p.Rules {
		if r.CeilingMbit <= 0 {
			continue
		}
		c := ceiling{Mbit: r.CeilingMbit, DownPipe: ceilDownBase + n, UpPipe: ceilUpBase + n}
		byKey[r.Key] = c
		list = append(list, c)
		n++
	}
	return list, byKey
}

// renderShaping returns the anchor text and the table contents to load with it.
func renderShaping(p core.ShapePlan) (string, map[string][]string) {
	var b strings.Builder
	tables := map[string][]string{}
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by FlowSight. Traffic shaping: the queue that decides what")
	w("# waits is moved onto this firewall, and these rules decide who waits.")
	w("# Matched on the LAN side, where addresses are not yet translated.")
	w("")
	if p.LAN == "" || len(p.Rules) == 0 && p.DefaultClass == "" {
		return "", tables
	}
	_, ceilings := shapeCeilings(p)

	for i, r := range p.Rules {
		if len(r.Addrs) == 0 {
			continue // a name nothing has resolved yet matches nothing, quietly
		}
		tables[shapeTable(i)] = r.Addrs
		w("table <%s> persist", shapeTable(i))
	}
	w("")

	// The default first, so a more specific rule later overrides it: pf takes
	// the last matching rule when none of them is quick, and none is.
	if p.DefaultClass != "" {
		w("# Everything starts in the %s class.", p.DefaultClass)
		w("match in on %s all dnqueue(%d)", p.LAN, classQueue(p.DefaultClass, false))
		w("match out on %s all dnqueue(%d)", p.LAN, classQueue(p.DefaultClass, true))
		w("")
	}

	for i, r := range p.Rules {
		if _, ok := tables[shapeTable(i)]; !ok {
			continue
		}
		t := shapeTable(i)
		side := "the far end"
		if r.Local {
			side = "this device"
		}
		w("# %s: %s", strings.TrimSpace(r.Label), side)
		// A device here is the source going out and the destination coming
		// back; something out there is the reverse.
		// Each direction needs its own rule. A queue named on a rule that
		// specifies "in" or "out" applies only to that direction, so the pair
		// form buys nothing here and the reply would go unshaped.
		sel, rev := "from <"+t+"> to any", "from any to <"+t+">"
		if !r.Local {
			sel, rev = "from any to <"+t+">", "from <"+t+"> to any"
		}
		if r.Class != "" {
			w("match in on %s %s dnqueue(%d)", p.LAN, sel, classQueue(r.Class, false))
			w("match out on %s %s dnqueue(%d)", p.LAN, rev, classQueue(r.Class, true))
		}
		if c, ok := ceilings[r.Key]; ok && r.CeilingMbit > 0 {
			w("match in on %s %s dnpipe(%d)", p.LAN, sel, c.UpPipe)
			w("match out on %s %s dnpipe(%d)", p.LAN, rev, c.DownPipe)
		}
		w("")
	}
	return b.String(), tables
}
