package firewall

import (
	"errors"
	"reflect"
	"strings"
	"testing"

	"github.com/grioghar/flowsight/internal/core"
)

// goldenShapePlan is what the qos module builds from these rules (see
// qos/qos_test.go, TestPlanMatchesFirewallGolden):
//
//	192.168.1.178 = low, 20Mbit
//	redgifs.com = high               resolved to two addresses
//	never-looked-up.example = high   resolved to nothing
//	203.0.113.9 = high
//	backup.example = 5               resolved to one address
//	10.0.5.0/24 = low
func goldenShapePlan() core.ShapePlan {
	return core.ShapePlan{LAN: "vtnet0", DownMbit: 93, UpMbit: 18.6, WeightHigh: 70, WeightNormal: 25, WeightLow: 5,
		DefaultClass: "normal", Rules: []core.ShapeRule{
			{Key: "10.0.5.0/24", Label: "10.0.5.0/24 = low", Addrs: []string{"10.0.5.0/24"}, Local: true, Class: "low"},
			{Key: "192.168.1.178", Label: "192.168.1.178 = low, 20Mbit", Addrs: []string{"192.168.1.178"}, Local: true, Class: "low", CeilingMbit: 20},
			{Key: "203.0.113.9", Label: "203.0.113.9 = high", Addrs: []string{"203.0.113.9"}, Class: "high"},
			{Key: "backup.example", Label: "backup.example = 5", Addrs: []string{"198.51.100.4"}, CeilingMbit: 5},
			{Key: "never-looked-up.example", Label: "never-looked-up.example = high", Class: "high"},
			{Key: "redgifs.com", Label: "redgifs.com = high", Addrs: []string{"203.0.113.7", "203.0.113.8"}, Class: "high"},
		}}
}

// The rules, tables and dnctl calls the qos module produced before its
// engine moved here, byte for byte.
func TestShapingGolden(t *testing.T) {
	text, tables := renderShaping(goldenShapePlan())
	want := `# Generated by FlowSight. Traffic shaping: the queue that decides what
# waits is moved onto this firewall, and these rules decide who waits.
# Matched on the LAN side, where addresses are not yet translated.

table <qos_r0> persist
table <qos_r1> persist
table <qos_r2> persist
table <qos_r3> persist
table <qos_r5> persist

# Everything starts in the normal class.
match in on vtnet0 all dnqueue(21)
match out on vtnet0 all dnqueue(11)

# 10.0.5.0/24 = low: this device
match in on vtnet0 from <qos_r0> to any dnqueue(22)
match out on vtnet0 from any to <qos_r0> dnqueue(12)

# 192.168.1.178 = low, 20Mbit: this device
match in on vtnet0 from <qos_r1> to any dnqueue(22)
match out on vtnet0 from any to <qos_r1> dnqueue(12)
match in on vtnet0 from <qos_r1> to any dnpipe(200)
match out on vtnet0 from any to <qos_r1> dnpipe(100)

# 203.0.113.9 = high: the far end
match in on vtnet0 from any to <qos_r2> dnqueue(20)
match out on vtnet0 from <qos_r2> to any dnqueue(10)

# backup.example = 5: the far end
match in on vtnet0 from any to <qos_r3> dnpipe(201)
match out on vtnet0 from <qos_r3> to any dnpipe(101)

# redgifs.com = high: the far end
match in on vtnet0 from any to <qos_r5> dnqueue(20)
match out on vtnet0 from <qos_r5> to any dnqueue(10)

`
	if text != want {
		t.Errorf("shaping rules changed:\n got: %q\nwant: %q", text, want)
	}
	wantTables := map[string][]string{
		"qos_r0": {"10.0.5.0/24"}, "qos_r1": {"192.168.1.178"}, "qos_r2": {"203.0.113.9"},
		"qos_r3": {"198.51.100.4"}, "qos_r5": {"203.0.113.7", "203.0.113.8"},
	}
	if !reflect.DeepEqual(tables, wantTables) {
		t.Errorf("tables changed: %v", tables)
	}

	var calls []string
	d := &dn{run: func(args ...string) (string, error) { calls = append(calls, strings.Join(args, " ")); return "", nil }}
	list, _ := shapeCeilings(goldenShapePlan())
	p := goldenShapePlan()
	if err := d.configure(plan{DownMbit: p.DownMbit, UpMbit: p.UpMbit, WeightHigh: p.WeightHigh,
		WeightNormal: p.WeightNormal, WeightLow: p.WeightLow, Ceilings: list}); err != nil {
		t.Fatal(err)
	}
	d.teardown(list)
	wantCalls := `pipe 1 config bw 93000Kbit/s queue 581250Bytes
pipe 2 config bw 18600Kbit/s queue 116250Bytes
sched 1 config pipe 1 type wf2q+
sched 2 config pipe 2 type wf2q+
queue 10 config sched 1 weight 70
queue 11 config sched 1 weight 25
queue 12 config sched 1 weight 5
queue 20 config sched 2 weight 70
queue 21 config sched 2 weight 25
queue 22 config sched 2 weight 5
pipe 100 config bw 20000Kbit/s queue 125000Bytes
pipe 200 config bw 20000Kbit/s queue 125000Bytes
pipe 101 config bw 5000Kbit/s queue 51200Bytes
pipe 201 config bw 5000Kbit/s queue 51200Bytes
queue delete 10
queue delete 11
queue delete 12
queue delete 20
queue delete 21
queue delete 22
sched delete 1
sched delete 2
pipe delete 100
pipe delete 200
pipe delete 101
pipe delete 201
pipe delete 1
pipe delete 2`
	if got := strings.Join(calls, "\n"); got != wantCalls {
		t.Errorf("dnctl calls changed:\n got:\n%s\nwant:\n%s", got, wantCalls)
	}
}

func TestShapingDirections(t *testing.T) {
	text, tables := renderShaping(core.ShapePlan{LAN: "vtnet0", DefaultClass: "normal", Rules: []core.ShapeRule{
		{Key: "192.168.1.178", Label: "192.168.1.178 = low", Addrs: []string{"192.168.1.178"}, Local: true, Class: "low"},
		{Key: "redgifs.com", Label: "redgifs.com = high", Addrs: []string{"203.0.113.7", "203.0.113.8"}, Class: "high"},
	}})
	if len(tables) != 2 {
		t.Fatalf("want a table per rule, got %d: %v", len(tables), tables)
	}
	for _, w := range []string{
		"match in on vtnet0 from <qos_r0> to any dnqueue(" + itoa(qUpLow) + ")",
		"match out on vtnet0 from any to <qos_r0> dnqueue(" + itoa(qDownLow) + ")",
		"match in on vtnet0 from any to <qos_r1> dnqueue(" + itoa(qUpHigh) + ")",
		"match out on vtnet0 from <qos_r1> to any dnqueue(" + itoa(qDownHigh) + ")",
	} {
		if !strings.Contains(text, w) {
			t.Errorf("missing rule:\n  %s\ngot:\n%s", w, text)
		}
	}
	// The default has to come first so a named rule can override it: pf takes
	// the last match when nothing is quick, and nothing here is.
	iDefault := strings.Index(text, "match in on vtnet0 all")
	iRule := strings.Index(text, "from <qos_r0> to any dnqueue")
	if iDefault < 0 || iRule < 0 || iDefault > iRule {
		t.Error("the default class must be emitted before the specific rules")
	}
	if strings.Contains(text, "quick") || strings.Contains(text, "pass ") || strings.Contains(text, "block ") {
		t.Error("shaping must only match, never be quick, pass or block")
	}
	if strings.Count(text, "match in on") != strings.Count(text, "match out on") {
		t.Errorf("each direction needs its own rule:\n%s", text)
	}
}

// A name nobody has resolved yet matches no addresses, so it must produce no
// table and no rule rather than an empty table that matches everything.
func TestShapingUnresolvedNameProducesNothing(t *testing.T) {
	text, tables := renderShaping(core.ShapePlan{LAN: "vtnet0", DefaultClass: "normal",
		Rules: []core.ShapeRule{{Key: "never-looked-up.example", Class: "high"}}})
	if len(tables) != 0 || strings.Contains(text, "qos_r0") {
		t.Errorf("an unresolved name must create neither table nor rule: %v\n%s", tables, text)
	}
	if !strings.Contains(text, "match in on vtnet0 all dnqueue(") {
		t.Error("the default class should still be applied")
	}
}

func TestShapingCeilingUsesItsOwnPipe(t *testing.T) {
	text, _ := renderShaping(core.ShapePlan{LAN: "vtnet0", DefaultClass: "normal", Rules: []core.ShapeRule{
		{Key: "192.168.1.178", Addrs: []string{"192.168.1.178"}, Local: true, Class: "low", CeilingMbit: 20}}})
	if !strings.Contains(text, "dnpipe("+itoa(ceilUpBase)+")") || !strings.Contains(text, "dnpipe("+itoa(ceilDownBase)+")") {
		t.Errorf("a ceiling must have a pipe on each direction:\n%s", text)
	}
	if !strings.Contains(text, "dnqueue("+itoa(qUpLow)+")") {
		t.Error("a rule with both a class and a ceiling must still get its class")
	}
}

// The buffer has to match the rate. Measured on a test gateway, the default
// fifty-slot queue held a 14 Mbit/s pipe to 4.6 Mbit/s of real throughput,
// because TCP was being told to back off by loss rather than by delay.
func TestQueueBytesTracksRate(t *testing.T) {
	if got := queueBytes(100); got != int(100e6/8*0.05) {
		t.Errorf("100 Mbit should buffer about 50ms of it, got %d bytes", got)
	}
	if got := queueBytes(0.1); got < 50<<10 {
		t.Errorf("a tiny pipe still needs a floor, got %d", got)
	}
	if got := queueBytes(10000); got > 2<<20 {
		t.Errorf("a huge pipe must be capped or the queue is just delay, got %d", got)
	}
}

func TestParseQueueStats(t *testing.T) {
	got := parseQueueStats("q00010  50 sl. 0 flows (1 buckets) sched 1 weight 70\nq00099 unrelated\nnot a queue\n")
	if len(got) != 1 || got[0].Queue != 10 || got[0].Name != "download high" {
		t.Errorf("queue stats misread: %+v", got)
	}
}

// After a reboot dummynet is not in the kernel, yet "dnctl pipe show" still
// succeeds; trusting it left shaping failing on every apply with "Protocol
// not available". The kernel is asked instead, and the module loaded.
func TestAvailableLoadsDummynetWhenTheKernelLacksIt(t *testing.T) {
	var sys []string
	loaded := false
	d := &dn{
		run: func(args ...string) (string, error) { return "", nil }, // dnctl answers either way
		sys: func(name string, args ...string) (string, error) {
			sys = append(sys, name+" "+strings.Join(args, " "))
			switch name {
			case "kldstat":
				if !loaded {
					return "", errors.New("exit status 1")
				}
			case "kldload":
				loaded = true
			}
			return "", nil
		},
	}
	if err := d.available(); err != nil {
		t.Fatal(err)
	}
	if !loaded {
		t.Fatalf("dummynet was not loaded; calls: %v", sys)
	}
	sys = nil
	if err := d.available(); err != nil || len(sys) != 1 || sys[0] != "kldstat -q -m dummynet" {
		t.Fatalf("with dummynet loaded, only the check should run: %v %v", err, sys)
	}
}
