package dns

// Local names: when the operator names a device in FlowSight, they can also
// give it a DNS name, so other devices reach it as nas.grio.co and a lookup
// of its address answers with that name.
//
// A name goes to every resolver the network's devices ask. The gateway's
// Unbound gets it from a FlowSight include (flowsight-names.conf), never
// from the operator's own host overrides, and it is loaded into the running
// resolver with unbound-control so the cache is not flushed. Each connected
// Pi-hole gets it as a local record, because a Pi-hole answers its clients
// from its own records and forwards everything else upstream, never to the
// gateway: a name only on the gateway is invisible to anyone using the
// Pi-hole directly.
//
// A device's IPv4 address changes when its lease does. With "follow" on,
// the name moves with the device: a job re-points it at the address the
// device's hardware address holds now.

import (
	"bufio"
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/grioghar/flowsight/internal/core"
	"github.com/grioghar/flowsight/internal/modules/pihole"
)

const (
	namesFileName = "flowsight-names.conf"
	namesKV       = "dns.local_names"
	namesTTL      = 300
)

type localName struct {
	FQDN    string   `json:"fqdn"`
	Label   string   `json:"label"`
	Domain  string   `json:"domain"`
	Display string   `json:"display,omitempty"`
	MAC     string   `json:"mac,omitempty"`
	Addrs   []string `json:"addresses"`
	Follow  bool     `json:"follow"`
	Gateway bool     `json:"gateway"`
	Piholes []string `json:"piholes"`
	// NoPTR lists addresses whose reverse name the gateway already answers
	// from the operator's own host overrides; FlowSight adds no second one.
	NoPTR   []string `json:"no_ptr,omitempty"`
	Created int64    `json:"created"`
	Updated int64    `json:"updated"`
	By      string   `json:"by,omitempty"`
}

type piholeHosts interface {
	Targets() []pihole.HostsTarget
	Hosts() map[string][]string
	EditHosts(servers []string, add, remove []string, actor, why string) []map[string]any
}

var (
	labelRe  = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)
	domainRe = regexp.MustCompile(`^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)
	namesMu  sync.Mutex // one change at a time: the file, the resolver and the Pi-holes move together
)

// labelFrom turns a display name into a DNS label: "Kitchen iPad (2)" ->
// "kitchen-ipad-2".
func labelFrom(display string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(display) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			dash = false
		default:
			if b.Len() > 0 && !dash {
				b.WriteByte('-')
				dash = true
			}
		}
	}
	s := strings.Trim(b.String(), "-")
	if len(s) > 63 {
		s = strings.Trim(s[:63], "-")
	}
	return s
}

// reverseName is the PTR owner name for an address.
func reverseName(ip string) string {
	a := net.ParseIP(ip)
	if a == nil {
		return ""
	}
	if v4 := a.To4(); v4 != nil {
		return fmt.Sprintf("%d.%d.%d.%d.in-addr.arpa.", v4[3], v4[2], v4[1], v4[0])
	}
	const hexd = "0123456789abcdef"
	var b strings.Builder
	for i := len(a) - 1; i >= 0; i-- {
		b.WriteByte(hexd[a[i]&0xf])
		b.WriteByte('.')
		b.WriteByte(hexd[a[i]>>4])
		b.WriteByte('.')
	}
	b.WriteString("ip6.arpa.")
	return b.String()
}

func rrType(ip string) string {
	if a := net.ParseIP(ip); a != nil && a.To4() == nil {
		return "AAAA"
	}
	return "A"
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

// renderNames is the Unbound include for every record the gateway serves.
func renderNames(recs []localName) string {
	var b strings.Builder
	b.WriteString("# Generated by flowsight: device names given in FlowSight (Settings › dns › Device names). Edit them there.\n")
	b.WriteString("server:\n")
	sort.Slice(recs, func(i, j int) bool { return recs[i].FQDN < recs[j].FQDN })
	for _, r := range recs {
		if !r.Gateway || len(r.Addrs) == 0 {
			continue
		}
		for _, a := range r.Addrs {
			fmt.Fprintf(&b, "    local-data: \"%s. %d IN %s %s\"\n", r.FQDN, namesTTL, rrType(a), a)
		}
		for _, a := range r.Addrs {
			if !contains(r.NoPTR, a) {
				fmt.Fprintf(&b, "    local-data-ptr: \"%s %d %s.\"\n", a, namesTTL, r.FQDN)
			}
		}
	}
	return b.String()
}

// piholeLines are the Pi-hole local records for one name: hosts form,
// which Pi-hole answers both forward and reverse.
func piholeLines(r localName) []string {
	var out []string
	for _, a := range r.Addrs {
		out = append(out, a+" "+r.FQDN)
	}
	return out
}

func (m *Module) loadNames() []localName {
	var recs []localName
	m.ctx.Store.KVGet(namesKV, &recs)
	return recs
}

func (m *Module) pihole() piholeHosts {
	p, _ := m.ctx.Service("pihole").(piholeHosts)
	return p
}

// hostEntries reads the operator's own host overrides from the gateway
// resolver's generated file: name -> addresses, and address -> names.
func (m *Module) hostEntries() (map[string][]string, map[string][]string) {
	fwd, rev := map[string][]string{}, map[string][]string{}
	if m.ctx.Platform.UnboundConfig == "" {
		return fwd, rev
	}
	f, err := os.Open(filepath.Join(filepath.Dir(m.ctx.Platform.UnboundConfig), "host_entries.conf"))
	if err != nil {
		return fwd, rev
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		q := strings.Index(line, "\"")
		if q < 0 {
			continue
		}
		body := strings.Fields(strings.Trim(line[q:], "\""))
		switch {
		case strings.HasPrefix(line, "local-data-ptr:") && len(body) >= 2:
			rev[body[0]] = append(rev[body[0]], strings.TrimSuffix(strings.ToLower(body[len(body)-1]), "."))
		case strings.HasPrefix(line, "local-data:") && len(body) >= 3:
			name := strings.TrimSuffix(strings.ToLower(body[0]), ".")
			fwd[name] = append(fwd[name], body[len(body)-1])
		}
	}
	return fwd, rev
}

// domains offers the local domains in use, most used first: the operator's
// host overrides, the Pi-holes' local domain, and the gateway's own.
func (m *Module) domains() []string {
	count := map[string]int{}
	fwd, _ := m.hostEntries()
	for name := range fwd {
		if i := strings.IndexByte(name, '.'); i > 0 && name != "localhost" {
			count[name[i+1:]] += 3
		}
	}
	if p := m.pihole(); p != nil {
		for _, t := range p.Targets() {
			if t.Domain != "" && t.Domain != "lan" {
				count[strings.ToLower(t.Domain)] += 2
			}
		}
	}
	if d := systemDomain(m.ctx.Platform.ConfigXML); d != "" {
		count[d]++
	}
	for _, r := range m.loadNames() {
		count[r.Domain]++
	}
	if d := strings.ToLower(core.Str(m.ctx.Settings(), "local_domain", "")); d != "" {
		count[d] += 1000
	}
	out := make([]string, 0, len(count))
	for d := range count {
		if domainRe.MatchString(d) && !strings.HasSuffix(d, "arpa") {
			out = append(out, d)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if count[out[i]] != count[out[j]] {
			return count[out[i]] > count[out[j]]
		}
		return out[i] < out[j]
	})
	return out
}

var systemDomainRe = regexp.MustCompile(`(?s)<system>.*?<domain>([^<]+)</domain>`)

func systemDomain(configXML string) string {
	if configXML == "" {
		return ""
	}
	b, err := os.ReadFile(configXML)
	if err != nil {
		return ""
	}
	if mm := systemDomainRe.FindSubmatch(b); mm != nil {
		return strings.ToLower(strings.TrimSpace(string(mm[1])))
	}
	return ""
}

// unboundControl runs one unbound-control command against the live resolver.
func (m *Module) unboundControl(args ...string) (string, error) {
	pl := m.ctx.Platform
	if pl.UnboundControl == "" {
		return "", fmt.Errorf("no unbound-control on this platform")
	}
	full := []string{}
	if pl.UnboundConfig != "" {
		full = append(full, "-c", pl.UnboundConfig)
	}
	return core.Run(20*time.Second, pl.UnboundControl, append(full, args...)...)
}

// applyGateway writes the include for every name (live and persistent
// copies), has the whole resolver configuration checked, reverts on
// rejection, and loads the touched names (before and after this change)
// into the running resolver without flushing its cache.
func (m *Module) applyGateway(before, after, all []localName) error {
	pl := m.ctx.Platform
	if pl.UnboundInclude == "" {
		return fmt.Errorf("this platform has no Unbound include directory")
	}
	dirs := uniq(filepath.Dir(pl.UnboundInclude), pl.UnboundPersistDir)
	text := renderNames(append([]localName(nil), all...))
	empty := !strings.Contains(text, "local-data")
	prev := map[string][]byte{}
	for _, d := range dirs {
		path := filepath.Join(d, namesFileName)
		if b, err := os.ReadFile(path); err == nil {
			prev[path] = b
		}
		if empty {
			_ = os.Remove(path)
			continue
		}
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path+".tmp", []byte(text), 0o644); err != nil {
			return err
		}
		if err := os.Rename(path+".tmp", path); err != nil {
			return err
		}
	}
	revert := func() {
		for _, d := range dirs {
			path := filepath.Join(d, namesFileName)
			if b, ok := prev[path]; ok {
				_ = os.WriteFile(path, b, 0o644)
			} else {
				_ = os.Remove(path)
			}
		}
	}
	if out, err := pl.UnboundCheck(); err != nil {
		revert()
		return fmt.Errorf("unbound-checkconf rejected the names, reverted: %s", firstLines(out, 3))
	}
	if !pl.UnboundRunning() {
		return nil // written; the resolver loads it when it starts
	}
	// Live: drop every name and reverse name this change touches, then add
	// the records as they now are.
	touched := map[string]bool{}
	for _, set := range [][]localName{before, after} {
		for _, r := range set {
			touched[r.FQDN+"."] = true
			for _, a := range r.Addrs {
				touched[reverseName(a)] = true
			}
		}
	}
	for n := range touched {
		_, _ = m.unboundControl("local_data_remove", n)
	}
	for _, r := range after {
		if !r.Gateway {
			continue
		}
		for _, a := range r.Addrs {
			if _, err := m.unboundControl("local_data", fmt.Sprintf("%s. %d IN %s %s", r.FQDN, namesTTL, rrType(a), a)); err != nil {
				return fmt.Errorf("written, but the running resolver refused %s: %v (it loads at the next reload)", r.FQDN, err)
			}
			if !contains(r.NoPTR, a) {
				_, _ = m.unboundControl("local_data", fmt.Sprintf("%s %d IN PTR %s.", reverseName(a), namesTTL, r.FQDN))
			}
		}
	}
	for n := range touched {
		_, _ = m.unboundControl("flush", n)
	}
	return nil
}

// applyPiholes moves each record's lines on the Pi-holes it names.
func (m *Module) applyPiholes(before, after []localName, actor string) []map[string]any {
	p := m.pihole()
	if p == nil {
		return nil
	}
	type edit struct{ add, remove []string }
	per := map[string]*edit{}
	get := func(u string) *edit {
		if per[u] == nil {
			per[u] = &edit{}
		}
		return per[u]
	}
	for _, r := range before {
		for _, u := range r.Piholes {
			get(u).remove = append(get(u).remove, piholeLines(r)...)
		}
	}
	for _, r := range after {
		for _, u := range r.Piholes {
			get(u).add = append(get(u).add, piholeLines(r)...)
		}
	}
	var out []map[string]any
	urls := make([]string, 0, len(per))
	for u := range per {
		urls = append(urls, u)
	}
	sort.Strings(urls)
	for _, u := range urls {
		e := per[u]
		// A line in both lists is unchanged: leave it where it is.
		keep := map[string]bool{}
		for _, l := range e.add {
			keep[l] = true
		}
		var rm []string
		for _, l := range e.remove {
			if !keep[l] {
				rm = append(rm, l)
			}
		}
		out = append(out, p.EditHosts([]string{u}, e.add, rm, actor, "updated from FlowSight's local names")...)
	}
	return out
}

// devAddrs lists the addresses a device holds, IPv4 first, most recent
// first, with whether each looks temporary (an IPv6 privacy address).
func (m *Module) devAddrs(ip, mac string) []map[string]any {
	rows, _ := m.ctx.Store.Rows(`SELECT ip, last_seen FROM hosts WHERE (lower(mac)=? AND ?<>'') OR ip=? ORDER BY last_seen DESC LIMIT 24`, strings.ToLower(mac), mac, ip)
	var v4, v6 []map[string]any
	seen := map[string]bool{}
	for _, r := range rows {
		a, _ := r["ip"].(string)
		pa := net.ParseIP(a)
		if pa == nil || seen[a] || pa.IsLinkLocalUnicast() || pa.IsLoopback() {
			continue
		}
		seen[a] = true
		row := map[string]any{"ip": a, "last_seen": r["last_seen"]}
		if pa.To4() != nil {
			v4 = append(v4, row)
			continue
		}
		// SLAAC from the hardware address (EUI-64) is stable; a random
		// interface identifier is a privacy address that rotates.
		stable := mac != "" && eui64Matches(pa, mac)
		row["stable"] = stable
		if !stable {
			row["note"] = "privacy address: the device replaces it every day or so"
		}
		v6 = append(v6, row)
	}
	return append(v4, v6...)
}

func eui64Matches(ip net.IP, mac string) bool {
	hw, err := net.ParseMAC(mac)
	if err != nil || len(hw) != 6 {
		return false
	}
	id := []byte{hw[0] ^ 2, hw[1], hw[2], 0xff, 0xfe, hw[3], hw[4], hw[5]}
	for i := 0; i < 8; i++ {
		if ip[8+i] != id[i] {
			return false
		}
	}
	return true
}

// resolverAt answers from one DNS server only.
func resolverAt(server string) *net.Resolver {
	return &net.Resolver{PreferGo: true, Dial: func(ctx context.Context, network, _ string) (net.Conn, error) {
		d := net.Dialer{Timeout: 1500 * time.Millisecond}
		return d.DialContext(ctx, "udp", net.JoinHostPort(server, "53"))
	}}
}

// checkAt reports what one server answers for a name and its addresses.
func checkAt(server string, r localName) map[string]any {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	res := resolverAt(server)
	got, _ := res.LookupHost(ctx, r.FQDN)
	fwdOK := len(r.Addrs) > 0
	for _, a := range r.Addrs {
		if !contains(got, a) {
			fwdOK = false
		}
	}
	rev := map[string][]string{}
	revOK := true
	for _, a := range r.Addrs {
		names, _ := res.LookupAddr(ctx, a)
		for i := range names {
			names[i] = strings.TrimSuffix(strings.ToLower(names[i]), ".")
		}
		rev[a] = names
		if !contains(names, r.FQDN) && !contains(r.NoPTR, a) {
			revOK = false
		}
	}
	return map[string]any{"server": server, "forward": got, "forward_ok": fwdOK, "reverse": rev, "reverse_ok": revOK}
}

func (m *Module) statusOf(r localName, targets []pihole.HostsTarget) []map[string]any {
	var servers []string
	if r.Gateway {
		servers = append(servers, "127.0.0.1")
	}
	for _, t := range targets {
		if contains(r.Piholes, t.URL) {
			servers = append(servers, t.Host)
		}
	}
	out := make([]map[string]any, len(servers))
	var wg sync.WaitGroup
	for i, s := range servers {
		wg.Add(1)
		go func(i int, s string) {
			defer wg.Done()
			out[i] = checkAt(s, r)
			if s == "127.0.0.1" {
				out[i]["label"] = "gateway resolver"
			} else {
				out[i]["label"] = "Pi-hole " + s
			}
		}(i, s)
	}
	wg.Wait()
	return out
}

// ---------------------------------------------------------------- API

func (m *Module) targets() (bool, []pihole.HostsTarget) {
	var t []pihole.HostsTarget
	if p := m.pihole(); p != nil {
		t = p.Targets()
	}
	return m.ctx.Platform.UnboundInclude != "", t
}

func (m *Module) apiNames(r *core.Req) (any, error) {
	recs := m.loadNames()
	gw, targets := m.targets()
	rows := make([]map[string]any, len(recs))
	var wg sync.WaitGroup
	for i, rec := range recs {
		wg.Add(1)
		go func(i int, rec localName) {
			defer wg.Done()
			rows[i] = map[string]any{"record": rec, "status": m.statusOf(rec, targets)}
		}(i, rec)
	}
	wg.Wait()
	return map[string]any{"names": rows, "domains": m.domains(), "gateway": gw, "piholes": targets}, nil
}

func (m *Module) apiNameSuggest(r *core.Req) (any, error) {
	ip, err := r.QSafe("ip", "", 64)
	if err != nil {
		return nil, err
	}
	if net.ParseIP(ip) == nil {
		return nil, core.BadRequest("ip must be an address")
	}
	display, err := r.QSafe("name", "", 80)
	if err != nil {
		return nil, err
	}
	mac := ""
	if rows, _ := m.ctx.Store.Rows(`SELECT COALESCE(mac,'') AS mac, COALESCE(name,'') AS name FROM hosts WHERE ip=?`, ip); len(rows) > 0 {
		mac, _ = rows[0]["mac"].(string)
		if display == "" {
			display, _ = rows[0]["name"].(string)
		}
	}
	gw, targets := m.targets()
	var existing *localName
	for _, rec := range m.loadNames() {
		if (mac != "" && strings.EqualFold(rec.MAC, mac)) || contains(rec.Addrs, ip) {
			rc := rec
			existing = &rc
			break
		}
	}
	_, rev := m.hostEntries()
	// What already answers for this device's addresses, so the page can
	// say "192.168.1.44 already reads as printer.grio.co".
	ptrs := map[string][]string{}
	for _, a := range m.devAddrs(ip, mac) {
		addr := a["ip"].(string)
		if n := rev[addr]; len(n) > 0 {
			ptrs[addr] = n
		}
	}
	doms := m.domains()
	return map[string]any{"ip": ip, "mac": mac, "label": labelFrom(display), "domains": doms,
		"addresses": m.devAddrs(ip, mac), "existing": existing, "reverse_taken": ptrs,
		"gateway": gw, "piholes": targets, "can_follow": mac != ""}, nil
}

func (m *Module) apiNameSave(r *core.Req) (any, error) {
	var in struct {
		Label     string   `json:"label"`
		Domain    string   `json:"domain"`
		Display   string   `json:"display"`
		IP        string   `json:"ip"`
		MAC       string   `json:"mac"`
		Addresses []string `json:"addresses"`
		Follow    bool     `json:"follow"`
		Gateway   bool     `json:"gateway"`
		Piholes   []string `json:"piholes"`
		Replace   string   `json:"replace"`
	}
	if err := r.Decode(&in); err != nil {
		return nil, err
	}
	label, domain := strings.ToLower(strings.TrimSpace(in.Label)), strings.Trim(strings.ToLower(strings.TrimSpace(in.Domain)), ".")
	if !labelRe.MatchString(label) {
		return nil, core.BadRequest("the name %q is not a valid DNS label: letters, digits and dashes, up to 63, not starting or ending with a dash", in.Label)
	}
	if !domainRe.MatchString(domain) || !strings.Contains(domain+".", ".") {
		return nil, core.BadRequest("the domain %q is not valid", in.Domain)
	}
	fqdn := label + "." + domain
	var addrs []string
	for _, a := range in.Addresses {
		p := net.ParseIP(strings.TrimSpace(a))
		if p == nil || p.IsLoopback() || p.IsUnspecified() || p.IsMulticast() || p.IsLinkLocalUnicast() {
			return nil, core.BadRequest("%q is not an address a device can be reached at", a)
		}
		if !contains(addrs, p.String()) {
			addrs = append(addrs, p.String())
		}
	}
	if len(addrs) == 0 {
		return nil, core.BadRequest("choose at least one address")
	}
	if !in.Gateway && len(in.Piholes) == 0 {
		return nil, core.BadRequest("choose where the name goes: the gateway resolver, a Pi-hole, or both")
	}
	mac := strings.ToLower(strings.TrimSpace(in.MAC))
	if mac == "" && in.IP != "" {
		if rows, _ := m.ctx.Store.Rows(`SELECT COALESCE(mac,'') AS mac FROM hosts WHERE ip=?`, in.IP); len(rows) > 0 {
			mac, _ = rows[0]["mac"].(string)
			mac = strings.ToLower(mac)
		}
	}
	_, targets := m.targets()
	var piholes []string
	for _, u := range in.Piholes {
		for _, t := range targets {
			if u == t.URL || u == t.Host {
				if !t.Writable {
					return nil, core.BadRequest("Pi-hole %s does not let FlowSight change its records; turn on “Permit app password to modify config” there, or leave it out", t.Host)
				}
				if !contains(piholes, t.URL) {
					piholes = append(piholes, t.URL)
				}
			}
		}
	}
	fwd, rev := m.hostEntries()
	if have := fwd[fqdn]; len(have) > 0 && in.Gateway {
		return nil, core.BadRequest("%s is already a host override on the gateway (%s); choose another name or change it in OPNsense › Unbound › Overrides", fqdn, strings.Join(have, ", "))
	}
	var noPTR []string
	for _, a := range addrs {
		if len(rev[a]) > 0 {
			noPTR = append(noPTR, a)
		}
	}

	namesMu.Lock()
	defer namesMu.Unlock()
	before := m.loadNames()
	var after, old []localName
	now := time.Now().Unix()
	created := now
	for _, rec := range before {
		same := rec.FQDN == fqdn || (in.Replace != "" && rec.FQDN == in.Replace) || (mac != "" && strings.EqualFold(rec.MAC, mac))
		if same {
			if rec.FQDN == fqdn && mac != "" && rec.MAC != "" && !strings.EqualFold(rec.MAC, mac) {
				return nil, core.BadRequest("%s already names another device (%s)", fqdn, rec.MAC)
			}
			old = append(old, rec)
			created = rec.Created
			continue
		}
		for _, a := range addrs {
			if contains(rec.Addrs, a) {
				return nil, core.BadRequest("%s already has the name %s in FlowSight; remove that first", a, rec.FQDN)
			}
		}
		after = append(after, rec)
	}
	rec := localName{FQDN: fqdn, Label: label, Domain: domain, Display: strings.TrimSpace(in.Display), MAC: mac, Addrs: addrs,
		Follow: in.Follow && mac != "", Gateway: in.Gateway, Piholes: piholes, NoPTR: noPTR, Created: created, Updated: now, By: r.User}
	after = append(after, rec)

	result := map[string]any{"record": rec}
	var notes []string
	if len(noPTR) > 0 {
		notes = append(notes, "The gateway already answers the reverse lookup for "+strings.Join(noPTR, ", ")+" from an OPNsense host override, so FlowSight adds the forward name only there.")
	}
	if in.Gateway || anyGateway(old) {
		if err := m.applyGateway(old, []localName{rec}, after); err != nil {
			result["gateway_error"] = err.Error()
		} else if in.Gateway {
			result["gateway"] = "ok"
		}
	}
	result["piholes"] = m.applyPiholes(old, []localName{rec}, r.User)
	if err := m.ctx.Store.KVSet(namesKV, after); err != nil {
		return nil, err
	}
	summary := fmt.Sprintf("DNS name %s -> %s", fqdn, strings.Join(addrs, ", "))
	if len(old) > 0 && old[0].FQDN != fqdn {
		summary += " (was " + old[0].FQDN + ")"
	}
	_ = m.ctx.Store.RecordChange("dns", "name:"+fqdn, r.User, "", strings.Join(addrs, ","), "", summary)
	result["notes"] = notes
	result["ok"] = result["gateway_error"] == nil && !anyError(result["piholes"])
	return result, nil
}

func anyGateway(recs []localName) bool {
	for _, r := range recs {
		if r.Gateway {
			return true
		}
	}
	return false
}

func anyError(v any) bool {
	list, _ := v.([]map[string]any)
	for _, x := range list {
		if x["error"] != nil {
			return true
		}
	}
	return false
}

func (m *Module) apiNameRemove(r *core.Req) (any, error) {
	var in struct {
		FQDN string `json:"fqdn"`
	}
	if err := r.Decode(&in); err != nil {
		return nil, err
	}
	namesMu.Lock()
	defer namesMu.Unlock()
	before := m.loadNames()
	var after, gone []localName
	for _, rec := range before {
		if rec.FQDN == strings.ToLower(strings.TrimSpace(in.FQDN)) {
			gone = append(gone, rec)
		} else {
			after = append(after, rec)
		}
	}
	if len(gone) == 0 {
		return nil, core.NotFound("no FlowSight name %s", in.FQDN)
	}
	result := map[string]any{}
	if anyGateway(gone) {
		if err := m.applyGateway(gone, nil, after); err != nil {
			result["gateway_error"] = err.Error()
		}
	}
	result["piholes"] = m.applyPiholes(gone, nil, r.User)
	if err := m.ctx.Store.KVSet(namesKV, after); err != nil {
		return nil, err
	}
	_ = m.ctx.Store.RecordChange("dns", "name:"+gone[0].FQDN, r.User, strings.Join(gone[0].Addrs, ","), "", "", "DNS name "+gone[0].FQDN+" removed")
	result["ok"] = result["gateway_error"] == nil && !anyError(result["piholes"])
	return result, nil
}

// followNames re-points names whose device moved to a new IPv4 address.
func (m *Module) followNames() error {
	namesMu.Lock()
	defer namesMu.Unlock()
	recs := m.loadNames()
	changed := false
	for i, rec := range recs {
		if !rec.Follow || rec.MAC == "" {
			continue
		}
		rows, _ := m.ctx.Store.Rows(`SELECT ip FROM hosts WHERE lower(mac)=? AND ip NOT LIKE '%:%' AND last_seen>=? ORDER BY last_seen DESC LIMIT 1`,
			strings.ToLower(rec.MAC), time.Now().Add(-6*time.Hour).Unix())
		if len(rows) == 0 {
			continue
		}
		now, _ := rows[0]["ip"].(string)
		var oldV4 []string
		var keep []string
		for _, a := range rec.Addrs {
			if p := net.ParseIP(a); p != nil && p.To4() != nil {
				oldV4 = append(oldV4, a)
			} else {
				keep = append(keep, a)
			}
		}
		if len(oldV4) != 1 || oldV4[0] == now || now == "" {
			continue // follows a single IPv4 address only
		}
		// Another FlowSight name already on that address wins.
		taken := false
		for j, other := range recs {
			if j != i && contains(other.Addrs, now) {
				taken = true
			}
		}
		if taken {
			continue
		}
		prev := rec
		rec.Addrs = append([]string{now}, keep...)
		rec.NoPTR = nil
		_, rev := m.hostEntries()
		for _, a := range rec.Addrs {
			if len(rev[a]) > 0 {
				rec.NoPTR = append(rec.NoPTR, a)
			}
		}
		rec.Updated = time.Now().Unix()
		recs[i] = rec
		if rec.Gateway {
			if err := m.applyGateway([]localName{prev}, []localName{rec}, recs); err != nil {
				m.ctx.Log.Warn("local name follow", "name", rec.FQDN, "error", err)
			}
		}
		m.applyPiholes([]localName{prev}, []localName{rec}, "flowsightd")
		_ = m.ctx.Store.RecordChange("dns", "name:"+rec.FQDN, "flowsightd", oldV4[0], now, "",
			fmt.Sprintf("DNS name %s followed its device from %s to %s", rec.FQDN, oldV4[0], now))
		changed = true
	}
	if changed {
		return m.ctx.Store.KVSet(namesKV, recs)
	}
	return nil
}

func (m *Module) registerNameRoutes(ctx *core.Context) {
	ctx.Every("follow-names", 2*time.Minute, m.followNames, core.Delayed())
	example := map[string]any{"fqdn": "kitchen-ipad.grio.co", "label": "kitchen-ipad", "domain": "grio.co", "display": "Kitchen iPad",
		"mac": "aa:bb:cc:dd:ee:ff", "addresses": []string{"192.168.1.44"}, "follow": true, "gateway": true,
		"piholes": []string{"https://192.168.1.53"}, "created": 1790500000, "updated": 1790500000}
	ctx.Route("GET", "/api/dns/names", m.apiNames,
		core.Doc("Device names FlowSight put in DNS, with what each resolver answers for them forward and reverse right now"),
		core.Returns("Local names", map[string]any{"domains": []string{"grio.co", "internal"}, "gateway": true,
			"piholes": []map[string]any{{"url": "https://192.168.1.53", "host": "192.168.1.53", "writable": true, "domain": "grio.co"}},
			"names": []map[string]any{{"record": example, "status": []map[string]any{{"label": "gateway resolver", "server": "127.0.0.1",
				"forward": []string{"192.168.1.44"}, "forward_ok": true, "reverse": map[string]any{"192.168.1.44": []string{"kitchen-ipad.grio.co"}}, "reverse_ok": true}}}}}))
	ctx.Route("GET", "/api/dns/names/suggest", m.apiNameSuggest,
		core.Doc("What to offer when naming a device: a DNS label from its name, the domains in use, its addresses, and where the name can go"),
		core.Query("ip", "string", "The device's address", true, "192.168.1.44"),
		core.Query("name", "string", "The display name being given, to derive the DNS label from", false, "Kitchen iPad"),
		core.Returns("Suggestion", map[string]any{"ip": "192.168.1.44", "mac": "aa:bb:cc:dd:ee:ff", "label": "kitchen-ipad", "domains": []string{"grio.co"},
			"addresses": []map[string]any{{"ip": "192.168.1.44", "last_seen": 1790500000}}, "existing": nil, "reverse_taken": map[string]any{},
			"gateway": true, "piholes": []map[string]any{{"url": "https://192.168.1.53", "host": "192.168.1.53", "writable": true}}, "can_follow": true}))
	ctx.Route("POST", "/api/dns/names", m.apiNameSave, core.Write(),
		core.Doc("Give a device a DNS name, forward and reverse, on the gateway resolver and chosen Pi-holes; replaces the device's previous name"),
		core.Body(core.Fld("label", "string", true, "Host label (letters, digits, dashes)", "kitchen-ipad"),
			core.Fld("domain", "string", true, "Local domain", "grio.co"),
			core.FldArr("addresses", true, "Addresses the name points at", core.Fld("", "string", false, "", "192.168.1.44")),
			core.Fld("gateway", "boolean", false, "Serve it from the gateway resolver", true),
			core.FldArr("piholes", false, "Pi-hole URLs to add it to", core.Fld("", "string", false, "", "https://192.168.1.53")),
			core.Fld("follow", "boolean", false, "Move the name when the device's IPv4 address changes (needs a MAC)", true),
			core.Fld("ip", "string", false, "The device's address, to find its MAC", "192.168.1.44"),
			core.Fld("mac", "string", false, "The device's MAC", "aa:bb:cc:dd:ee:ff"),
			core.Fld("display", "string", false, "The display name, for the record", "Kitchen iPad"),
			core.Fld("replace", "string", false, "A FlowSight name this one replaces", "old-name.grio.co")),
		core.Returns("Saved", map[string]any{"ok": true, "record": example, "gateway": "ok", "piholes": []map[string]any{{"host": "192.168.1.53", "ok": true}}, "notes": []string{}}))
	ctx.Route("POST", "/api/dns/names/remove", m.apiNameRemove, core.Write(),
		core.Doc("Remove a device name FlowSight put in DNS, from the gateway resolver and the Pi-holes"),
		core.Body(core.Fld("fqdn", "string", true, "The name to remove", "kitchen-ipad.grio.co")),
		core.Returns("Removed", map[string]any{"ok": true, "piholes": []map[string]any{{"host": "192.168.1.53", "ok": true}}}))
}
